pipeline {
    agent any
    
    tools {
        maven 'maven 3.6.1'
    }
    
    stages {
        stage("Build") {
            steps {
                echo 'Compiling worker app'
                dir('worker') {
                    sh 'mvn compile'
                }
            }
        }
        
        stage("Test") {
            steps {
                echo 'Running Unit Tests on worker app'
		dir ('worker'){
			sh 'mvn compile test'
		}
            }
        }
        
        stage("Package") {
            steps {
                echo 'Packaging worker app'
                dir ('worker'){
                        sh 'mvn package'
                }

            }
        }
    }
    
    post {
        always {
            echo 'Building multibranch pipeline for worker is completed.'
        }
    }
}

